server:
  port: 8082

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12341234
  thymeleaf:
    cache: false
#    여기
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-name: kakao
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
#            client-id: ecf7e443a56627d29bfcc53a5fa9e752
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/auth
#            token-uri: https://kauth.kakao.com/oauth/foken
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#            client-secret: tLZpxYJpeEAvKfsEhPuiWjLpdaZAH4E7
#            client-authentication-method: POST
#            scope: profile, nickname, account_email

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#
#mvc:
#  pathmatch:
#    matching-strategy: ant_path_matcher