server:
  port: 8083

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12341234
  thymeleaf:
    cache: false
  oauth:
    kakao:
      client-id: ecf7e443a56627d29bfcc53a5fa9e752
      url:
        auth: https://kauth.kakao.com
        api: https://kapi.kakao.com
    naver:
      secret: ES7OAIfSla
      client-id: ea2Onbn7lRo86vyj6sN8
      url:
        auth: https://nid.naver.com
        api: https://openapi.naver.com

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#
#mvc:
#  pathmatch:
#    matching-strategy: ant_path_matcher